//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Console
    {
        public int id { get; set; }
        public string name { get; set; }
        public int brand_id { get; set; }
        public System.DateTime release_date { get; set; }
        public int storage_capacity { get; set; }
        public decimal price { get; set; }
        public string comment { get; set; }
        public int user_created_id { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> user_modified_id { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public bool is_active { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Brand Brand1 { get; set; }
    }
}
